use sicoi;
insert into pais VALUES(1,'México');
insert into estado values(1,1,'Aguascalientes'),(2,1,'Baja California'),(3,1,'Baja California Sur'),(4,1,'Campeche'),(5,1,'Chiapas'),
(6,1,'Chihuahua'),(7,1,'Coahuila de Zaragoza'),(8,1,'Colima'),(9,1,'Durango'),(10,1,'Estado de México'),(11,1,'Guanajuato'),
(12,1,'Guerrero'),(13,1,'Hidalgo'),(14,1,'Jalisco'),(15,1,'Michoacán de Ocampo'),(16,1,'Morelos'),(17,1,'Nayarit'),(18,1,'Nuevo León'),
(19,1,'Oaxaca'),(20,1,'Puebla'),(21,1,'Querétaro'),(22,1,'Quintana Roo'),(23,1,'San Luis Potosí'),(24,1,'Sinaloa'),(25,1,'Sonora'),
(26,1,'Tabasco'),(27,1,'Tamaulipas'),(28,1,'Tlaxcala'),(29,1,'Veracruz'),(30,1,'Yucatán'),(31,1,'Zacatecas');
insert into municipio values(1,1,'Armería'),(2,1,'Colima'),(3,1,'Comala'),(4,1,'Coquimatlán'),(5,1,'Cuauhtémoc'),(6,1,'Ixtlahuacán'),(7,1,'Manzanillo'),(8,1,'Minatitlán'),(9,1,'Tecomán'),(10,1,'Villa de Álvarez');
insert into localidad values (1,3,'Comala'),(2,3,'Cofradía de Suchitlán'),(3,3,'Suchitlán'),(4,3,'Zacualpan');

INSERT INTO `tipo_aviso` VALUES ('1', 'Via 066');
INSERT INTO `tipo_aviso` VALUES ('2', 'Local');
INSERT INTO `tipo_aviso` VALUES ('3', 'Institucional');
insert into `tipo_reporte` values(1,'Seguridad Publica'),(2,'Vialidad'),(3,'Ayuntamiento'),(4,'Médica');
INSERT INTO `lugar` VALUES ('1', '1', 'Capitan A. LLerenas s/n colona La Trinidad', '0', '0');
INSERT INTO `privilegio` VALUES ('1', 'Administrador'),('2', 'Policia'),('3', 'Prevención'),('4', 'usuario');

Insert into `emergencia` (`nombre`,`tipo`) values ( 'Ingreso a Barandilla', '1'), ('ABANDONO DE VEHÍCULO',2),('ABORTO',1),('ABUSO SEXUAL',1),
('ACCIDENTE ACUÁTICO CON HERIDOS',2),('ACCIDENTE DE AERONAVE CON HERIDOS',2),('ACCIDENTE DE MOTOCICLETA CON HERIDOS',2),
('ACCIDENTE DE TRANSITO SIN HERIDOS',2),('ACCIDENTE DE VEHICULO AUTOMOTOR CON HERIDOS',2),('ACCIDENTE FERROVIARIO CON HERIDOS',2),
('ACOSO ESCOLAR O BULLING',1),('ACOSO U HOSTIGAMIENTO SEXUAL',1),('ACTOS DE COMERCIALIZACION ILEGAL DE SANGRE,ORGANOS O TEJIDOS HUMANOS',1),
('AERONAVE SOSPECHOSA',1),('AFECTACION DE LOS SERVICIOS BASICOS',3),('AGRESION FISICA',1),('AHOGADO',4),('ALARMA DE EMERGENCIA ACTIVADA',1),
('ALCANTARILLA OBSTRUIDA',3),('ALCANTARILLA SIN TAPA',3),('ALLANAMIENTO DE MORADA',1),('ALMACENAMIENTO DE SUBSTANCIAS PELIGROSAS',1),
('ALTERACION DEL ORDEN PUBLICO POR PERSONA ALCOHOLIZADA',1),('ALTERACION DEL ORDEN PUBLICO POR PERSONA DROGADA',1),('AMENAZA DE ABORTO',4),('AMENAZA DE BOMBA',1),
('AMENAZA DE SUICIDIO',1),('AMENAZA O INSULTO',1),('AMPUTADO',4),('ANIMAL MUERTO',3),('ANIMAL PELIGROSO',3),('APOYO PSICOLÓGICO',4),('ÁRBOL CAIDO O POR CAER',3),
('ARRANCONES O CARRERAS DE VEHÍCULOS',1),('ASFIXIA',4),('ASOCIACIÓN DELICTUOSA O PANDILLERISMO',1),('ATAQUES AL PUDOR',1),('ATROPELLADO',2),('ATROPELLAMIENTO DE SEMOVIENTE',2)
,('BLOQUEO DE VÍAS DE COMUNICACIÓN',2),
('BOTÓN DE ACTIVADO DE EMERGENCIA',1),('CABLES COLGANDO',3),('CADÁVER',4),('CAÍDA DE ANUNCIO ESPECTACULAR',3),('CAÍDA DE BARDA',3),
('CAÍDA DE POSTE DE LUZ',3),('CAÍDA DE POSTE DE TELEFÓNICO',3),('CAÍDA EN LUGAR PROFUNDO',4),('CIRCULAR EN SENTIDO CONTRARIO',1),
('COLISIÓN CON HERIDOS',2),('CONDUCTOR EBRIO',1),('CONGESTIÓN ALCOHOLICA',4),('CONSUMO DE ALCOHOL EN VÍA PÚBLICA',1),('CONSUMO DE DROGAS EN VÍA PÚBLICA',1),
('CONTAMINACIÓN DE SUERO,AIRE Y AGUA',3),('CONVULSIONES',4),('CORRUPCIÓN DE MENORES',1),('CORTO CIRCUITO',3),('CRISIS NERVIOSA',4),
('CRISTALAZO',1),('DAÑO A BIENES PÚBLICOS INSTITUCIONES MONUMENTOS ENTRE OTROS',1),('DAÑO A PROPIEDAD AJENA',1),
('DEMOSTRACIONES DE INCONFORMIDAD SOCIAL',3),('DERRUMBES',3),('DESCARGA DE DERECHOS SIN PERMISOS',1),('DESMAYO',4),
('DESPOJO',1),('DETONACIÓN DE EXPLOSIVOS',1),('DISPARO DE ARMA DE FUEGO',1),('ELECTORALES',1),('ELECTROCUTADO',4),('ENFERMO',4),
('ENFERMO MENTAL',4),('ENFRENTAMIENTO DE GRUPOS ARMADOS',1),('ENJAMBRE DE ABEJAS',3),('EPIDEMIAS',3),('ERUPCIÓN O EMISIONES VOLCÁNICAS',3),
('ESTUPRO',1),('EXPLOSIÓN',3),('EXPLOTACIÓN DE MENORES',1),('EXTORSIÓN',1),('EXTORSIÓN VÍA TELEFÓNICA',1),('FALLA DE ALUMBRADO PÚBLICO',3),
('FALLAS DE SEMÁFORO',3),('FETO HUMANO ENCONTRADO',1),('FRACTURADO',4),('FRAUDE',1),('FRENTES FRÍOS, BAJAS TEMPERAUTRAS, NEVADAS Y HELADAS',3),
('FUGA DE AGUA',3),('FUGA DE REOS',1),('FUGAS Y DERRAMES',3),('GRAFFITIS',1),('GRAVA SUELTA',3),
('HALLAZGO DE ARMA',1),('HALLAZGO DE OSAMENTA O RESTOS HUMANOS',1),('HEMORRAGIA',4),('HOMICIDIO',1),
('HUNDIMIENTOS REGIONALES, LOCALES Y AGRIETAMIENTOS',3),('HURACANES',3),('INCENDIO',3),('INCONSCIENTE',4),('INFARTO',4),('INTOXICACIÓN',4),('INUNDACIONES',3),
('LESIONADO POR ARMA',4),('LESIONADO POR CAÍDA',4),('MALTRATO DE ANIMALES',3),('MANIFESTACIÓN CON DISTURBIS O BLOQUEOS',1),('MENOR EXTRAVIADO',1),
('MITIN',1),('MORDIDA ANIMAL',4),('NARCOMENUDEO',1),('OBJETO SOSPECHOSO O PELIGROSO',1),('OLORES',3),('OTRAS LESIONES',4),
('OTROS ATENTADOS CONTRA EL PATRIMONIO',1),('OTROS ATENTADOS CONTRA LA FAMILIA',1),('OTROS ATENTADOS CONTRA LA LIBERTAD PERSONAL',1),
('OTROS ATENTADOS CONTRA LA SOCIEDAD',1),('OTROS ATENTADOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL',1),('OTROS SERVICIOS PÚBLICOS',3),
('PELEA CLANDESTINA CON ANIMALES',1),('PELEA CLANDESTINA O RIÑA',1),('PERSONA AGRESIVA',1),('PERSONA EN SITUACIÓN DE CALLE',3),
('PERSONA ENVENENADA',4),('PERSONA EXHIBICIONISTA',1),('PERSONA NO LOCALIZADA',1),('PERSONA PRENSADA',3),('PERSONA SOSPECHOSA',1),
('PERSONA TIRADA EN VÍA PÚBLICA',4),('PIQUETE DE ANIMAL',4),('PLAGAS',3),('PORTACIÓN DE ARMAS O CARTUCHOS',1),
('PRIVACIÓN DE LA LIBERTAD',1),('QUEMADURAS',4),('RECUPERACIÓN DE VEHÍCULO ROBADO',1),('REHENES',1),
('RESCATE',3),('RESIDUOS PELIGROSOS',3),('ROBO A BANCO CON VIOLENCIA',1),('ROBO A BANCO SIN VIOLENCIA',1),('ROBO A CAJERO AUTOMÁTICO',1),
('ROBO A CASA DE CAMBIO CON VIOLENCIA',1),('ROBO A CASA DE CAMBIO SIN VIOLENCIA',1),('ROBO A CASA HABITACIÓN CON VIOLENCIA',1),
('ROBO A CASA HABITACIÓN SIN VIOLENCIA',1),('ROBO A EMPRESA DE TRASLADO DE VALORES CON VIOLENCIA',1),('ROBO A EMPRESA DE TRASLADO DE VALORES SIN VIOLENCIA',1),
('ROBO A ESCUELA CON VIOLENCIA',1),('ROBO A ESCUELA SIN VIOLENCIA',1),('ROBO A FERROCARRIL',1),('ROBO A GASOLINERA CON VIOLENCIA',1),
('ROBO A GASOLINERA SIN VIOLENCIA',1),('ROBO A NEGOCIO CON VIOLENCIA',1),('ROBO A NEGOCIO SIN VIOLENCIA',1),
('ROBO A TRANSEUNTE CON VIOLENCIA',1),('ROBO A TRANSEUNTE SIN VIOLENCIA',1),('ROBO A TRANSPORTISTA CON VIOLENCIA',1),
('ROBO A TRANSPORTISTA SIN VIOLENCIA',1),('ROBO DE AUTOPARTES',1),
('ROBO DE COMBUSTIBLE O TOMA COLANDESTINA DE DUCTOS',1),('ROBO DE GANADO',1),('ROBO DE GANADO EN PROCESO',1),
('ROBO DE VEHÍCULO PARTICULAR CON VIOLENCIA',1),('ROBO DE VEHÍCULO PARTICULAR SIN VIOLENCIA',1),('ROBO EN CARRETERA CON VIOLENCIA',1),
('ROBO EN CARRETERA SIN VIOLENCIA',1),('ROBO EN PROCESO A BANCO CON VIOLENCIA',1),('ROBO EN PROCESO A BANCO SIN VIOLENCIA',1),
('ROBO EN PROCESO A CASA DE CAMBIO CON VIOLENCIA',1),('ROBO EN PROCESO A CASA DE CAMBIO SIN VIOLENCIA',1),('ROBO EN PROCESO A CASA HABITACIÓN CON VIOLENCIA',1),
('ROBO EN PROCESO A CASA HABITACIÓN SIN VIOLENCIA',1),('ROBO EN PROCESO A EMPRESA DE TRASLADO DE VALORES CON VIOLENCIA',1),
('ROBO EN PROCESO A EMPRESA DE TRASLADO DE VALORES SIN VIOLENCIA',1),('ROBO EN PROCESO A ESCUELA CON VIOLENCIA',1),('ROBO EN PROCESO A ESCUELA SIN VIOLENCIA',1),
('ROBO EN PROCESO A FERROCARRIL',1),('ROBO EN PROCESO A GASOLINERA CON VIOLENCIA',1),('ROBO EN PROCESO A GASOLINERA SIN VIOLENCIA',1),
('ROBO EN PROCESO A NEGOCIO CON VIOLENCIA',1),('ROBO EN PROCESO A NEGOCIO SIN VIOLENCIA',1),('ROBO EN PROCESO A TRANSEUNTE CON VIOLENCIA',1),
('ROBO EN PROCESO A TRANSEUNTE SIN VIOLENCIA',1),('ROBO EN PROCESO A TRANSPORTISTA CON VIOLENCIA',1),('ROBO EN PROCESO A TRANSPORTISTA SIN VIOLENCIA',1),
('ROBO EN PROCESO DE VEHÍCULO PARTICULAR CON VIOLENCIA',1),('ROBO EN PROCESO DE VEHICULO PARTICULAR SIN VIOLENCIA',1),('ROBO EN TRANSPORTE PÚBLICO COLECTIVO CON VIOLENCIA',1),
('ROBO EN TRANSPORTE PÚBLICO COLECTIVO SIN VIOLENCIA',1),('ROBO EN TRANSPORTE PÚBLICO INDIVIDUAL CON VIOLENCIA',1),('ROBO EN TRANSPORTE PÚBLICO INDIVIDUAL SIN VIOLENCIA',1),
('ROBO O EXTRAVÍO DE PLACA',1),('RUIDO EXCESIVO',1),('SECUESTRO',1),('SECUESTRO EXPRESS',1),('SIMULACRO',3),('SISMO',3),('SOBREDOSIS',4),('SUICIDIO',1),
('SUSTRACCIÓN DE MENORES',1),('TALA ILEGAL',3),('TERRORISMO O ATENTADO',1),('TORMENTAS DE GRANIZO',3),('TORNADOS',3),('TRABAJO DE PARTO',4),
('TRASNPORTE DE SUBSTANCIAS PELIGROSAS',3),('TRATA DE MENORES',1),('TRATA DE PERSONAS',1),('TRÁFICO DE INDOCUMENTADOS',1),('TRÁFICO DE MENORES',1),('TSUNAMI',3),
('USURPACIÓN DE IDENTIDAD',1),('VEHÍCULO A EXCESO DE VELOCIDAD',1),('VEHÍCULO DE HUIDA',1),('VEHÍCULO SOSPECHOSO',1),
('VENTA CLANDESTINA DE PIROTÉCNIA, COHETES O FUEGOS ARTIFICIALES',1),('VIALIDAD EN MAL ESTADO',1),('VIENTO',3),('VIOLACIÓN',3),('VIOLACIÓN A LA LEY DE JUEGOS Y SORTEOS',1),('VIOLACIÓN DE SELLOS DE CLAUSURA',1),('VIOLACIÓN CONTRA LA MUJER',1),
('VIOLENCIA DE PAREJA',1),('VIOLENCIA FAMILIAR',1),('VOLCADURA CON HERIDOS',2);